version: '3.4'
services:
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: local/elmo_base

  hg:
    build: hgmo
    command: hg --cwd /data/repos serve -p 8001 --webdir-conf=/app/webdir.conf
    ports:
     - "8001:8001"
    volumes:
     # not using storage, those are reading the client-side, we need upstream
     - ./stage/hgmo:/data/repos
     - ~/.mozbuild/version-control-tools:/app/version-control-tools
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
  a10n:
    build:
      context: .
      dockerfile: a10n/Dockerfile
    image: elmo-a10n
  hg-poller:
    command:
      - bash
      - -c
      - . /app/env/bin/activate; cd /app/a10n; rm twistd.pid; PYTHONPATH=. twistd -n --umask 0077 get-pushes
    image: elmo-a10n
    environment:
      - ELMO_TRANSPORT=amqp://foopy:foopy@rabbitmq:5672
      - ELMO_DB_HOST=${ELMO_DB_HOST}
      - ELMO_DB_NAME=${ELMO_DB_NAME}
      - ELMO_DB_USER=${ELMO_DB_USER}
      - ELMO_DB_PASSWORD=${ELMO_DB_PASSWORD}
      - ELMO_SECRET_KEY="still just testing"
      - ELMO_REPOSITORY_BASE=/data/repos
    volumes:
     - ./stage/repos:/data/repos
    links:
      - rabbitmq
    depends_on:
      # rabbitmq:
      #   condition: service_healthy
      - hg
  a10n-hg-worker:
    command:
      - bash
      - -c
      - . /app/env/bin/activate; cd /app/a10n; ./scripts/a10n hg
    image: elmo-a10n
    environment:
      - ELMO_TRANSPORT=amqp://foopy:foopy@rabbitmq:5672
      - ELMO_DB_HOST=${ELMO_DB_HOST}
      - ELMO_DB_NAME=${ELMO_DB_NAME}
      - ELMO_DB_USER=${ELMO_DB_USER}
      - ELMO_DB_PASSWORD=${ELMO_DB_PASSWORD}
      - ELMO_SECRET_KEY="still just testing"
      - ELMO_REPOSITORY_BASE=/data/repos
    volumes:
     - ./stage/repos:/data/repos
    links:
      - rabbitmq
    depends_on:
      # rabbitmq:
      #   condition: service_healthy
      - hg
  bb:
    build: 
      context: .
      dockerfile: bb/Dockerfile
      args:
        shares: /data/shares
        master: test-master
    environment:
      - ELMO_DB_HOST=${ELMO_DB_HOST}
      - ELMO_DB_NAME=${ELMO_DB_NAME}
      - ELMO_DB_USER=${ELMO_DB_USER}
      - ELMO_DB_PASSWORD=${ELMO_DB_PASSWORD}
      - ELMO_SECRET_KEY="still just testing"
      - ELMO_REPOSITORY_BASE=/data/repos
      - ELMO_BUILD_BASE=/data/builds
      - ELMO_HG_SHARES=/data/shares
      - ES_COMPARE_HOST=elasticsearch:9200
      - ES_COMPARE_INDEX=elmo-comparisons
    volumes:
      - ./stage/builds:/data/builds
      - ./stage/repos:/data/repos
    links:
      - hg
      - elasticsearch
    depends_on:
      - hg
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=foopy
      - RABBITMQ_DEFAULT_PASS=foopy
    # Doing healthcheck would be great, if it worked.
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "-ufopy:foopy", "http://localhost:15672/api/overview"]
    #   retries: 5
  elasticsearch:
    image: elasticsearch:2.4.5
    ports:
    - "9200:9200"
# volumes:
#   repos:
#   builds:
