version: '3.4'
services:
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: local/elmo_base

  hg:
    build: hgmo
    command: hg --cwd /data/repos serve -p 8001 --webdir-conf=/app/webdir.conf
    ports:
     - "8001:8001"
    volumes:
     # not using storage, those are reading the client-side, we need upstream
     - ./stage/hgmo:/data/repos
     - ~/.mozbuild/version-control-tools:/app/version-control-tools
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
  a10n:
    build:
      context: .
      dockerfile: a10n/Dockerfile
    command: /app/entrypoint.sh
    volumes:
     - ./a10n/a10n:/app/a10n
     - ./stage/repos:/data/repos
    links:
      - rabbitmq
    depends_on:
      # rabbitmq:
      #   condition: service_healthy
      - hg
  bb:
    build: 
      context: .
      dockerfile: bb/Dockerfile
      args:
        shares: /data/shares
    command: /app/entrypoint.sh
    volumes:
      - ./bb/master-ball:/app/master-ball
      - ./stage/builds:/data/builds
      - ./stage/repos:/data/repos
    links:
      - hg
      - elasticsearch
    depends_on:
      - hg
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=foopy
      - RABBITMQ_DEFAULT_PASS=foopy
    # Doing healthcheck would be great, if it worked.
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "-ufopy:foopy", "http://localhost:15672/api/overview"]
    #   retries: 5
  elasticsearch:
    image: elasticsearch:2.4.5
    ports:
    - "9200:9200"
# volumes:
#   repos:
#   builds:
